#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if npx --no -- commitlint --edit "$1"; then
  echo "Nje commit i bukur. Vazhdojme tutje 😃😎"
else
  echo "Ka je nis o jarano 🤬. Kqyr prap cka je ka don me bo commit 🤯"
  exit 1
fi
